/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CompHome: typeof import('./components/CompHome.vue')['default']
    CompSearch: typeof import('./components/CompSearch.vue')['default']
    ResultPlaylists: typeof import('./components/ResultPlaylists.vue')['default']
    ResultTabs: typeof import('./components/ResultTabs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
